# docker-compose.yml

version: "3"
services:
  frontend:
    build:
      context: ./mycad-frontend
    ports:
      - "5173:80"

  backend:
    build:
      context: ./mycad-backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/mycad
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mycad
