services:
  backend:
    build:
      env:
        - DATABASE_URL=${{ secrets.DATABASE_URL }} # Asegúrate de tener la URL correcta
    environment:
      NODE_ENV: production
    deploy:
      steps:
        - run: npm install # Instala las dependencias del proyecto
        - run: npx prisma generate # Genera el cliente de Prisma
        - run: npx prisma migrate deploy # Aplica las migraciones de Prisma
        - run: pm2-runtime src/index.js # Comando para iniciar la aplicación
